build-job:
  stage: build
  script:
    - echo "Hello, $GITLAB_USER_LOGIN!, building bin file"
    - sh bdwb django-app.wb

deploy-job:
  stage: deploy
  script:
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."

cleanup_job:
  stage: .post
  script:
    - echo "Cleaning up"
    - rm -rf "%CACHE_PATH%/%CI_PIPELINE_ID%"
  when: always
